# All times in no of frames
REACTION_TIME: 90
FIX_CROSS_TIME: 60
STIM_TIME: 3600
FRAME_RATE: 60
REACTION_KEYS: [left, right, up, down, f7]
NUMBER_OF_TRIALS: 12
EXIT_KEY: f7
AFTER_TRAINING_TIME: 120
FIX_CROSS_COLOR: black
REMINDER_COLOR: black
STIM_COLOR: black
BACKGROUND_COLOR: darkgray
NO_BLOCKS: 3